# -*- coding: utf-8 -*-
"""producer_wikipageviews (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-W5iOWYhaPsfk1_kr2oJcZjBZh-GSs_r
"""

!pip install confluent-kafka

import gzip
from confluent_kafka import Producer
import time

# Kafka configuration
KAFKA_BOOTSTRAP_SERVERS = 'localhost:9092'  # Adjust to your Kafka server
KAFKA_TOPIC = 'wiki-pageviews'

# Producer configuration
producer_conf = {
    'bootstrap.servers': KAFKA_BOOTSTRAP_SERVERS
}
producer = Producer(producer_conf)

# Callback for handling delivery reports
def delivery_report(err, msg):
    if err:
        print(f"Delivery failed: {err}")
    else:
        print(f"Message delivered to {msg.topic()} [{msg.partition()}]")

from datetime import datetime

# Extract date and hour from filename
def extract_date_hour(filename):
    # Example filename: pageviews-20240101-220000.gz
    try:
        date_str = filename.split('-')[1]  # '20240101'
        hour_str = filename.split('-')[2][:2]  # '22'
        date = datetime.strptime(date_str, '%Y%m%d').strftime('%Y-%m-%d')
        hour = hour_str
        return date, hour
    except (IndexError, ValueError):
        print("Filename format is incorrect. Expected format: 'pageviews-YYYYMMDD-HHmmss.gz'")
        return None, None

# Load and send file lines to Kafka
def publish_wiki_pageviews(filepath):
    date, hour = extract_date_hour(filepath)
    if date is None or hour is None:
        return
    count = 0
    with gzip.open(filepath, 'rt', encoding='utf-8') as f:
        for line in f:
            count+=1
            print(count)
            # Add date and hour to each line
            enriched_line = f"{date} {hour} {line.strip()}"
            producer.produce(KAFKA_TOPIC, value=enriched_line, callback=delivery_report)
            producer.poll(0)  # Polls to ensure delivery reports are handled
            time.sleep(0.01)  # Adjust to control publishing rate

    producer.flush()  # Ensure all messages are delivered

publish_wiki_pageviews('pageviews-20240101-220000.gz')